### ISSUE TITLE
verify actual topic given

### ISSUE THREAD

**Issue by kohljd** [Brain-Defrost/Brain-Defrost_BE#26]
"asdflkjqwerljnasdv", "asdf623489$%%^", etc. shouldn't be accepted as valid topics

A gem like this may be useful: https://github.com/ereslibre/realtime-validations

**Comment by laurarvegav** [comment]
@kohljd actually pointed out that it is no needed, given that ChatOpenAI API will choose topic Random when the string doesn't make sense!
