### ISSUE TITLE
Email Stats to received emails

### ISSUE THREAD

**Issue by laurarvegav** [Brain-Defrost/Brain-Defrost_BE#60]
Background task [lesson](https://backend.turing.edu/module3/lessons/intro_to_background_workers)
Turing Rails email [lesson](https://backend.turing.edu/module3/lessons/sending_email_in_rails)
Rails Action Mailer [guide](https://guides.rubyonrails.org/action_mailer_basics.html)

Let FE know which endpoint will be used for this.
- [ ] update Postman mock server
- [ ] update API docs

**Comment by kohljd** [comment]
FE plans to send game's ID and the email to send the game's stats to.
FE would like to receive a confirmation message that the email is on it's way.

BE mtg notes:
- POST `api/v1/:id/email` (id is game's id)
- JSON response w/message that email is on it's way
